// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using labclothingcollection.Context;

#nullable disable

namespace labclothingcollection.Migrations
{
    [DbContext(typeof(labclothingcollectionContext))]
    [Migration("20230621102317_R3")]
    partial class R3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("labclothingcollection.Models.Colecao", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<DateTime>("AnoLancamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Orcamento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Identificador");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Colecoes");
                });

            modelBuilder.Entity("labclothingcollection.Models.Modelo", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<int>("ColecaoId")
                        .HasColumnType("int");

                    b.Property<string>("LayoutPeca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoPeca")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Identificador");

                    b.HasIndex("ColecaoId");

                    b.ToTable("Modelos");
                });

            modelBuilder.Entity("labclothingcollection.Models.Usuario", b =>
                {
                    b.Property<int>("Identificador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identificador"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Identificador");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Identificador = 1,
                            Cpf = "365412365",
                            Email = "teste@teste.com",
                            Genero = "masculino",
                            Nascimento = new DateTime(1990, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "João da Silva",
                            Status = "Ativo",
                            Telefone = "9512328",
                            Tipo = "Administrador"
                        },
                        new
                        {
                            Identificador = 2,
                            Cpf = "874596321",
                            Email = "exemplo@example.com",
                            Genero = "feminino",
                            Nascimento = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Maria Souza",
                            Status = "Ativo",
                            Telefone = "987654321",
                            Tipo = "Gerente"
                        },
                        new
                        {
                            Identificador = 3,
                            Cpf = "123456789",
                            Email = "usuario@dominio.com",
                            Genero = "masculino",
                            Nascimento = new DateTime(1998, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Pedro Santos",
                            Status = "Inativo",
                            Telefone = "456789123",
                            Tipo = "Criador"
                        },
                        new
                        {
                            Identificador = 4,
                            Cpf = "987654321",
                            Email = "exemplo2@example.com",
                            Genero = "feminino",
                            Nascimento = new DateTime(1987, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Ana Rodrigues",
                            Status = "Ativo",
                            Telefone = "321654987",
                            Tipo = "Outro"
                        });
                });

            modelBuilder.Entity("labclothingcollection.Models.Colecao", b =>
                {
                    b.HasOne("labclothingcollection.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("labclothingcollection.Models.Modelo", b =>
                {
                    b.HasOne("labclothingcollection.Models.Colecao", "Colecao")
                        .WithMany()
                        .HasForeignKey("ColecaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colecao");
                });
#pragma warning restore 612, 618
        }
    }
}
